version: '3'

services:
    db:
        container_name: "${PROJECT_NAME}_db"
        image: mysql:5.7
        volumes:
            - './.docker/db:/docker-entrypoint-initdb.d'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'P455W0RD'
        ports:
            - '3306:3306'
    mail:
        container_name: "${PROJECT_NAME}_mail"
        image: tophfr/mailcatcher
        ports:
            - '1080:80'
    php:
        build:
            context: .docker/php-fpm
            dockerfile: Dockerfile
            args:
                - DOCKER_UID=${DOCKER_UID:-1000}
                - DOCKER_GID=${DOCKER_GID:-1000}
        container_name: "${PROJECT_NAME}_php"
        working_dir: /app
        volumes:
            - .:/app
            - ./.docker/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ~/.ssh/:/root/.ssh/
        environment:
            PHP_IDE_CONFIG: 'serverName=localhost:80'
    nginx:
        image: nginx:1-alpine
        container_name: "${PROJECT_NAME}_nginx"
        volumes:
            - .:/app
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/ssl/:/etc/ssl/docker/
        ports:
            - "80:80"
            - "443:443"
